### ISSUE TITLE
About reproducing Table 4 in Appendix G

### ISSUE THREAD

**Issue by haebeom-lee** [flennerhag/warpgrad#7]
Hi Flannerhag,

Congratulations for the nice work! I really enjoyed reading your paper.

Just a simple question about reproducing Table 4 in Appendix G. Could you let me know the reference code you used for KFAC? Or, do you have any plan to release your code for KFAC or any other baseline experiments based on random initializations?

And also, could you provide a brief explanation about to how use run_multi.py?

Thank you!

Best regards,
Hae Beom Lee.

**Comment by flennerhag** [comment]
Hi, 

Glad to hear you liked it! : ) 

Nowadays there are quite a few repo's out there, I'd expect any of them to reproduce (under the same hyper-params). For the paper, we used [this one](https://github.com/Thrandis/EKFAC-pytorch) by the original authors of E-KFAC. 

As for `run_multi.py`, it basically lets you exectute the `main.py` script for a given model over a range of pre-training tasks, for a given number of seeds per tasks. You can load and inspect the results in a notebook using the `monitor.FileHandler` class.
